cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --account=HENDERSON-SL3-CPU
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --time={resources.time}
    --job-name=MA1_2-{rule}-{wildcards}
    --output=logs/{rule}/{wildcards}-%j.out
    --error=logs/{rule}/{wildcards}-%j.err
default-resources:
  - partition=skylake
  - mem_mb=1000
  - time="12:00:00"
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
